<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Leden Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'Isbek2110@gmail.com',
		'to' => 'Isbek2110@gmail.com'
	),
	'fields' => array(
		'custom_U3021' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Naam en voornaam',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Naam en voornaam\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'E-mail',
			'required' => false,
			'errors' => array(
				'format' => 'Field \'E-mail\' has an invalid email.'
			)
		),
		'custom_U3520' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Klas',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Klas\' is required.'
			)
		),
		'custom_U3532' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Geboortedatum',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U3544' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Geslacht',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Geslacht\' is required.'
			)
		),
		'custom_U3648' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Reden voor je keuze',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U3556' => array(
			'order' => 6,
			'type' => 'checkboxgroup',
			'label' => 'Keuze Functie',
			'required' => true,
			'optionItems' => array(
				'Prime Minister',
				'2nd to 10th Seat',
				'Helpers',
				'Leden'
			),
			'errors' => array(
				'required' => 'Field \'Keuze Functie\' is required.',
				'format' => 'Field \'Keuze Functie\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
